/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiple;

import java.awt.Font;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author NOUR SOFT
 */
public class ShowGame extends javax.swing.JFrame {

    /**
     * Creates new form ShowGame
     */
    
    JLabel [] label = new JLabel[9];
    public ShowGame() {
        initComponents();
        label[0] = label0;
        label[1] = label1;
        label[2] = label2;
        label[3] = label3;
        label[4] = label4;
        label[5] = label5;
        label[6] = label6;
        label[7] = label7;
        label[8] = label8;
        
    }
    
    
    
     public void showdata(String date, String local)
    {
        
        String FilegameDate;
        String FilePlayerName1;
        String FilePlayerScore1;
        String FilePlayerName2;
        String FilePlayerScore2;
        System.out.println("data\n" +date);
        int btn1;
        String value;
        LinkedHashMap<Integer, String> moves = new LinkedHashMap<>();
        String[] splitline = local.split("/n");
        
        for(int x = 0; x<splitline.length; x++)
        {
            
            String [] line = splitline[x].split(",");
            FilegameDate = line[0];
            System.out.println("data\n" +date);
            if(FilegameDate.equalsIgnoreCase(date))
            {
                System.out.println("inside FilegameDate\n" +FilegameDate);
                FilePlayerName1 = line[1];
                FilePlayerScore1 = line[2];
                FilePlayerName2 = line[3];
                FilePlayerScore2 = line[4];
                labelFirstPlayerName.setText(FilePlayerName1);
                labelFirstScore.setText(FilePlayerScore1);
                labelSecondPlayerName.setText(FilePlayerName2);
                labelSecondScore.setText(FilePlayerScore2);    

                
                
                for (int j = 5, k = 6; j < line.length  && k < line.length ; j += 2, k += 2) {
                    btn1 = Integer.parseInt(line[j]);
                    value = line[k];
                    moves.put(btn1, value);
                    System.out.println("aaaaaaaaaaaaaaaaaaaaaaaaaaaa" + btn1 + "/" + value);
                }
                
            
            System.out.println("out side for loop");
            Thread n = new Thread(new Runnable() {
                @Override
                public void run() {
                    
                
                for (int key:moves.keySet())
                {
                    try {
                        System.out.print(key+" string in button::"+moves.get(key)+"\n");
                        //label[key].setFont(new Font("Arial", Font.BOLD, 0));
                        label[key].setText(moves.get(key));
                        if((moves.get(key)).equals("X"))
                            label[key].setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/x.png")));
                        else if((moves.get(key)).equals("O"))
                            label[key].setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/o.png")));
                        
                        
                        Thread.sleep(1000);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ShowGame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            
                }
            });
            n.start(); 
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label0 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();
        labelFirstPlayerName = new javax.swing.JLabel();
        labelSecondPlayerName = new javax.swing.JLabel();
        labelFirstScore = new javax.swing.JLabel();
        labelSecondScore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(214, 229, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label0.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label0.setForeground(new java.awt.Color(214, 229, 250));
        label0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 80, 80));

        label1.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label1.setForeground(new java.awt.Color(214, 229, 250));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 80, 80));

        label2.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label2.setForeground(new java.awt.Color(214, 229, 250));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 80, 80));

        label3.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label3.setForeground(new java.awt.Color(214, 229, 250));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 80));

        label4.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label4.setForeground(new java.awt.Color(214, 229, 250));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 80, 80));

        label5.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label5.setForeground(new java.awt.Color(214, 229, 250));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 80, 80));

        label6.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label6.setForeground(new java.awt.Color(214, 229, 250));
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, 80));

        label7.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label7.setForeground(new java.awt.Color(214, 229, 250));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 80, 80));

        label8.setFont(new java.awt.Font("Agency FB", 0, 3)); // NOI18N
        label8.setForeground(new java.awt.Color(214, 229, 250));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 80, 80));

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/board_1.png"))); // NOI18N
        jPanel1.add(imagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        labelFirstPlayerName.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jPanel1.add(labelFirstPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        labelSecondPlayerName.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jPanel1.add(labelSecondPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        labelFirstScore.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jPanel1.add(labelFirstScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        labelSecondScore.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jPanel1.add(labelSecondScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vs.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagelabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel labelFirstPlayerName;
    private javax.swing.JLabel labelFirstScore;
    private javax.swing.JLabel labelSecondPlayerName;
    private javax.swing.JLabel labelSecondScore;
    // End of variables declaration//GEN-END:variables
}
